### ISSUE TITLE
Deadline: 15 maggio ore 23.59 per creare la cartella vetrina

### ISSUE THREAD

**Issue by tmontanaro** [SoNet-2017/YOUniverse#4]
Ciao ragazzi, siete l'unico gruppo a non aver creato la cartella "vetrina". Perciò vi dò ancora tempo fino a stasera, dopo di che creerò il sito vetrina senza il vostro progetto!
Buona giornata
Teo

**Comment by Cosmopoliti** [comment]
Ok, provvediamo subito

2017-05-15 10:41 GMT+02:00 Teodoro Montanaro <notifications@github.com>:

**Comment by tmontanaro** [comment]
Grazie! Posso chiedervi ancora un favore? Potreste rinominare la cartella "Vetrina" in "vetrina" (lettera minuscola)?
Altrimenti se mi date l'ok (quindi non fate modifiche fino a quando non vi dò ok) rinomino io e poi fate pull!

**Comment by Cosmopoliti** [comment]
modifico subito

2017-05-15 12:17 GMT+02:00 Teodoro Montanaro <notifications@github.com>:
